version: '3.9'

services:
  mssql:
    container_name: gfwpro-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    restart: always


networks: 
  default: 
    external: 
      name: gfwpro-network 